<?xml version="1.0"?>
<testResults>
  <FitNesseVersion>v20200108</FitNesseVersion>
  <rootPath>FrontPage.RentTest.Login</rootPath>
  <executionLog>
    <testSystem>fit:fit.FitServer</testSystem>
    <command>/usr/lib/jvm/java-13-openjdk-amd64/bin/java -cp /home/piotrek/studia/5_sem/io/projekt2/fitnesse-standalone.jar:/home/piotrek/studia/5_sem/io/projekt2/build/classes/java/main/ fit.FitServer chaz 34251 3863</command>
    <exitCode>1</exitCode>
    <stdOut></stdOut>
    <stdErr>Exception in thread "main" java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:493)
	at java.base/sun.nio.ch.Net.connect(Net.java:482)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:339)
	at java.base/java.net.Socket.connect(Socket.java:585)
	at java.base/java.net.Socket.connect(Socket.java:534)
	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:457)
	at java.base/java.net.Socket.&lt;init&gt;(Socket.java:231)
	at fit.FitServer.establishConnection(FitServer.java:150)
	at fit.FitServer.establishConnection(FitServer.java:146)
	at fit.FitServer.run(FitServer.java:54)
	at fit.FitServer.main(FitServer.java:41)
</stdErr>
    <exception>FitClient external process terminated before a connection could be established</exception>
    <exception>FitClient external process terminated before a connection could be established</exception>
  </executionLog>
  <finalCounts>
    <right>0</right>
    <wrong>0</wrong>
    <ignores>0</ignores>
    <exceptions>1</exceptions>
  </finalCounts>
  <totalRunTimeInMillis>1244</totalRunTimeInMillis>
</testResults>

